# Generated by Django 5.2.5 on 2025-11-09 02:28

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('years_experience', models.IntegerField(default=0)),
                ('specialties', models.TextField(help_text='Comma-separated list of specialties')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Information',
                'verbose_name_plural': 'Business Information',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(help_text='Main project image', upload_to='portfolio/main/')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='portfolio/thumbnails/')),
                ('gallery_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='portfolio/gallery/')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='portfolio/before/')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='portfolio/after/')),
                ('before_thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='portfolio/before/thumbnails/')),
                ('after_thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='portfolio/after/thumbnails/')),
                ('is_before_after', models.BooleanField(default=False, help_text='Is this a before/after project?')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='category.category')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='portfolio/images/thumbnails/')),
                ('gallery_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='portfolio/images/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='gallery.portfolioitem')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='portfolio/videos/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated from video', null=True, upload_to='portfolio/videos/thumbnails/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='gallery.portfolioitem')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_range', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Hide inactive services')),
                ('display_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='category.category')),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='gallery.service'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'is_active'], name='gallery_ser_categor_d36797_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['display_order'], name='gallery_ser_display_779c17_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='gallery_ser_name_6001e5_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['category', 'upload_date'], name='gallery_por_categor_cc5756_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['service', 'upload_date'], name='gallery_por_service_d72aee_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['is_before_after', 'upload_date'], name='gallery_por_is_befo_65ed9e_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['title'], name='gallery_por_title_b7030c_idx'),
        ),
    ]
